config_name = 'template'

[dataset]
path_kilogram = './kilogram/dataset/'
path_concrete_images = './concrete_images/'

[score_net]
num_fc_layers = 4
hidden_dim = 64
embed_dim = 32

[cnn_backbone]
model = 'VGG16'

[segmentation_model]
model_type = 'vit_h'
checkpoint = 'sam_vit_h_4b8939.pth'

[training]
learning_rate = 0.0002
num_epochs = 500000
batch_size = 1016
t_max = 0.05
t_decay = false
